config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/secret", to: "static_pages#secret"

  get 'users/new'
  get 'users/show'
  get 'users/edit'
  get 'users/index'

  resources :users

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  				    uniqueness: { case_sensitive: false },
  				    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Mauvaise combinaison email/password gros!"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
  	unless logged_in?
  		redirect_to login_path
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
    	redirect_to @user
    else
    	render "new"
    end
  end

  def show
    @user = current_user
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = current_user
  	@user.update(user_params)
    redirect_to @user
  end

  def index
  	@users = User.all
  end

  def destroy
  	@user = current_user
  	@user.destroy
  	redirect_to users_path
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	  def log_in(user)
		  session[:user_id] = user.id
	  end

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
    	!current_user.nil?
    end

    def log_out
    	session.delete(:user_id)
    	@current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Mayson", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Index", users_index_path %></li>
          <li><%= link_to "Mon profil", user_path(current_user) %></li>
          <li><%= link_to "Deconnexion", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Se connecter", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<h1>StaticPages#home</h1>

<% if logged_in? %>
  <%= link_to "Découvrir le secret de l'Univers", secret_path, class: "btn btn-primary" %>
<% else %>
  <p><%= link_to "Créer un profil", new_user_path, class: "btn btn-primary" %> ou 
  <%= link_to "Se connecter", login_path, class: "btn btn-primary" %></p>
<% end %>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<h1>StaticPages#secret</h1>

  <p align="center">C'est cadeau 🎁</p>
  <p align="center"><iframe width="560" height="315" src="https://www.youtube.com/embed/CWA_be_9G_k?autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe><p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<h1>Users#edit</h1>
<h1>Editer mon profil</h1>

    <%= form_for @user, url: {action: "update"}, html: {class: "nifty-form"} do |f| %>

      <%= f.label "Email" %>
      <%= f.email_field :email %>

      <%= f.label "Password" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>      

      <%= f.submit "Updater mon profil", class: "btn-primary" %>

    <% end %>

<%= link_to "Détruire mon profil", @user, method: :delete, class: "btn btn-danger" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<h1>Users#index</h1>
<h1>Index</h1>

<table>

	<% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>	
      <td><%= user.email %></td>
      <% if user == current_user %>
      <td><%= link_to 'Voir le profil', user_path(user), class: "btn btn-primary" %></td>
      <td><%= link_to 'Editer les informations', edit_user_path(user), class: "btn btn-primary" %></td>
      <td><%= link_to "Supprimer le profil", user, method: :delete,  class: "btn btn-danger" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<h1>Users#new</h1>
<h1>Créer un nouvel utilisateur</h1>

    <%= form_for @user, url: {action: "create"}, html: {class: "nifty-form"} do |f| %>

      <%= f.label "Email" %>
      <%= f.email_field :email %>

      <%= f.label "Password" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>      

      <%= f.submit "Let's go !", class: "btn btn-lg btn-primary" %>
    <% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<h1>Users#show</h1>
<h1>Mon profil</h1>

<%= @user.email %>

<%= link_to "Editer mon profil", edit_user_path(@user), class: "btn btn-primary" %>

<%= link_to "Supprimer mon profil", @user, method: :delete, class: "btn btn-danger" %>